1062: Encryption tweaks
OS2Forms/os2forms pull request #114
Opened 2024-06-25 11:01 UTC by jekuaitk

https://leantime.itkdev.dk/tickets/showKanban?tab=ticketdetails#/tickets/showTicket/1062

2024-06-25 14:00 UTC, cableman requested changes

2024-06-25 14:01 UTC, cableman commented
Maybe even more documentation on the storage class, why all this is needed.

2024-06-25 14:14 UTC, jekuaitk commented on modules/os2forms_encrypt/src/WebformOs2FormsEncryptSubmissionStorage.php
> +  protected function loadData(array &$webform_submissions) {
Yes, `WebformEncryptSubmissionStorage::loadData` calls `WebformSubmissionStorage::loadData` before decrypting resulting in computed elements being computed before having their values decrypted.

In our case this result in the classic `TypeError: Unsupported operand types: string * int in __TwigTemplate__`.

2024-06-25 14:24 UTC, jekuaitk commented
> Maybe even more documentation on the storage class, why all this is needed.

Added extra section to class documentation.

2024-06-26 07:52 UTC, cableman approved these changes

2024-06-26 07:55 UTC, merged