Undo all of my previous changes
OS2Forms/os2forms pull request #75
Opened 2023-11-09 14:36 UTC by inuitviking

This removes all my previous changes in my latest (and also closed) pull request ([#72](https://github.com/OS2Forms/os2forms/pull/72)), as I believe it did not properly solve the issue; also, this helps clean up the mess I made in develop - sorry about that. :)

2023-11-09 15:15 UTC, stanbellcom requested changes

2023-11-09 15:15 UTC, stanbellcom commented on composer.json
> +        },
tab/formatting issue

2023-11-09 15:15 UTC, stanbellcom commented on src/Form/SettingsForm.php
> +
we don't need that, do we?

2023-11-09 15:26 UTC, inuitviking commented on src/Form/SettingsForm.php
> +
Checks wouldn't pass without it.

2023-11-09 15:26 UTC, inuitviking commented on composer.json
> +        },
Fixed

2023-11-10 08:02 UTC, rimi-itk requested changes

2023-11-10 08:02 UTC, rimi-itk commented on CHANGELOG.md
> +  Closed this pull request, and undid changes in develop
Since this is a clean up (revert of changes) we should not mention it in the change log, i.e. remove this line plus the line above it.

2023-11-10 08:07 UTC, rimi-itk commented
> @rimi-itk do you accept this way of undoing the previous changes in develop? that reverts #72

@stanbellcom, if the changes undo all changes from https://patch-diff.githubusercontent.com/raw/OS2Forms/os2forms/pull/72 it should be fine. 

@inuitviking, can you use https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request#reverting-a-pull-request to revert the changes rather than doing it manually?

2023-11-10 09:48 UTC, inuitviking commented
> > @rimi-itk do you accept this way of undoing the previous changes in develop? that reverts #72
> 
> @stanbellcom, if the changes undo all changes from https://patch-diff.githubusercontent.com/raw/OS2Forms/os2forms/pull/72 it should be fine.
> 
> @inuitviking, can you use https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/reverting-a-pull-request#reverting-a-pull-request to revert the changes rather than doing it manually?

This would require a merge of the pull request first, and only then can the pull request be reverted, as the article you linked to mentions.

Considering the changes have been made on develop (instead of a separate branch as it should have been) and the pull request is to merge develop into master, I personally think it would be better to merge this pull request, and keep the manual reversion I have made.

2023-11-10 12:12 UTC, stanbellcom approved these changes

2023-11-10 13:50 UTC, rimi-itk approved these changes

2023-11-10 13:51 UTC, merged